version: '3'

services:  
  api-server:    
    build:
      context: ./k8.docker.app.server.user
      dockerfile: Dockerfile
    image: k8_server_user:rc1
    ports :
    - "8081:5002"
  api-client:    
    build: 
      context: ./k8.docker.app.client.user
      dockerfile: Dockerfile
    image: k8_client_user:rc2
    ports :
      - "8080:5001"
    environment:
      Server_URI: "http://api-server:5002/" 
    depends_on:
      - api-server 


  